# Generated by Django 5.0 on 2023-12-18 22:05

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('personal', 'Personal'), ('family', 'Family'), ('work', 'Work'), ('miscellaneous', 'Miscellaneous'), ('other', 'Other')], default='action', max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01000000000000000020816681711721685132943093776702880859375')), django.core.validators.MaxValueValidator(9999999.99)])),
                ('description', models.TextField(blank=True, null=True)),
                ('date_added', models.DateField(auto_now=True)),
                ('category', models.CharField(blank=True, choices=[('fees', 'Fees'), ('transport', 'Transport'), ('communication', 'Communication'), ('other', 'Other')], max_length=50, null=True)),
            ],
        ),
    ]
