# Generated by Django 5.0 on 2023-12-19 01:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='date_completion',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(float("inf"))]),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='category',
            field=models.CharField(blank=True, choices=[('fees', 'Fees'), ('transport', 'Transport'), ('communication', 'Communication')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='title',
            field=models.CharField(choices=[('personal', 'Personal'), ('family', 'Family'), ('work', 'Work'), ('miscellaneous', 'Miscellaneous')], default='action', max_length=200),
        ),
    ]
