# Generated by Django 5.0 on 2023-12-19 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_alter_expenses_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expenses',
            old_name='date_completion',
            new_name='date_completed',
        ),
    ]
