# Generated by Django 5.0 on 2023-12-21 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_rename_date_completion_expenses_date_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='date_added',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
